name = "stellarhal"

description = "Stellarhal library"

version = "0.1.0-dev"

authors = ["Célian Aldehuelo-Mateos, Vladislav Kupin"]
maintainers = ["Vladislav Kupin <vlad.kupin@proton.me>"]
maintainers-logins = ["axterd"]

licenses = "MIT"

website = "https://github.com/evolutek"

tags = [
    "embedded",
    "stm32",
    "stellarhal",
    "evolutek",
]

[[depends-on]]
stm32f4xxm_devebox = "0.1.0"

[[pins]]
gnat_arm_elf = { version='12.2.1' }
