name = "uart"
description = "Abstract UART interface"
version = "0.1.0"

authors = ["Célian Aldehuelo-Mateos, Vladislav Kupin"]
maintainers = ["Vladislav Kupin <vlad.kupin@proton.me>"]
maintainers-logins = ["axterd"]
licenses = "BSD-3-Clause"
website = "https://github.com/evolutek"
tags = ["embedded", "stm32", "stellarhal", "evolutek"]

[[depends-on]]
gnat_arm_elf = "^12"
hal = "~0.3.0"
