name = "pa1616d"
description = "pa1616d driver"
version = "0.1.0-dev"

authors = ["Vladislav Kupin"]
maintainers = ["Vladislav Kupin <vlad.kupin@proton.me>"]
maintainers-logins = ["axterd"]
licenses = "BSD-3-Clause"
website = "https://github.com/evolutek"
tags = ["embaded", "stm32", "stellahal", "evolutek"]

[[depends-on]]
stm32f4xxm_devebox = "0.1.0"

[[pins]]
gnat_arm_elf = { version='12.2.1' }
uart = { path = '../uart' }
